name: CI - RDP Setup

on: [push, workflow_dispatch]

jobs:
  setup_rdp:
    runs-on: windows-latest

    steps:
    # التحقق من الاتصال بالإنترنت
    - name: Check Internet Connection
      shell: powershell
      run: |
        $max_attempts = 3
        $attempt = 1
        while ($attempt -le $max_attempts) {
          try {
            $response = Test-Connection -ComputerName "google.com" -Count 1 -ErrorAction Stop
            Write-Output "Internet connection established."
            break
          } catch {
            if ($attempt -eq $max_attempts) {
              Write-Output "No internet connection after $max_attempts attempts."
              exit 1
            } else {
              Write-Output "Attempt $attempt failed. Retrying in 5 seconds..."
              Start-Sleep -Seconds 5
              $attempt++
            }
          }
        }

    # تفعيل بروتوكول سطح المكتب البعيد (RDP) وتحديث جدار الحماية
    - name: Enable Remote Desktop Protocol (RDP)
      shell: powershell
      run: |
        try {
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name "fDenyTSConnections" -Value 0
          Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
          Write-Output "RDP has been enabled."
        } catch {
          Write-Output "Error enabling RDP."
          exit 1
        }

    # تعيين كلمة المرور للمستخدم المخصص
    - name: Set Password for Custom User
      shell: powershell
      run: |
        $username = "User123_Admin"  # اسم المستخدم هنا
        $password = ConvertTo-SecureString "S3cureP@ssw0rd!2024" -AsPlainText -Force  # كلمة المرور هنا
        $user = Get-WmiObject Win32_UserAccount -Filter "Name='$username'"
        if ($user) {
          Write-Output "User found, setting password..."
          try {
            ([ADSI]("WinNT://$env:COMPUTERNAME/$username,user")).SetPassword($password)
            Write-Output "Password set successfully."
          } catch {
            Write-Output "Error setting password."
            exit 1
          }
        } else {
          Write-Output "User not found, creating user..."
          try {
            New-LocalUser -Name $username -Password $password -PasswordNeverExpires
            Add-LocalGroupMember -Group "Remote Desktop Users" -Member $username
            Write-Output "User created and added to Remote Desktop Users group."
          } catch {
            Write-Output "Error creating user or setting permissions."
            exit 1
          }
        }

    # عرض معلومات الوصول عن بعد
    - name: Display Remote Access Information
      shell: powershell
      run: |
        try {
          $ipAddress = (Invoke-RestMethod -Uri "https://api.ipify.org").Trim()
          Write-Output "You can access the RDP server using IP: $ipAddress with username 'User123_Admin'."
        } catch {
          Write-Output "Error retrieving public IP address."
          exit 1
        }

    # تنظيف الملفات المؤقتة
    - name: Cleanup Temporary Files
      if: always()
      shell: powershell
      run: |
        Write-Output "Cleaning up temporary files..."
        # ضع هنا أي أوامر تنظيف إضافية تحتاجها
